# Generated by Django 2.2.4 on 2019-09-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190927_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='related_to_comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
