# Generated by Django 2.2.4 on 2019-11-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191102_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='blog.Post'),
        ),
    ]
