# Generated by Django 2.2.5 on 2019-11-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191114_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Undefined', 'UNDEFINED'), ('Sport', 'SPORT'), ('Art', 'ART'), ('Nature', 'NATURE'), ('Tech', 'TECH'), ('Culture', 'CULTURE'), ('Programming', 'PROGRAMMING')], default='Undefined', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
